version: '2'
services:
  web:
    build: ./
    # image: richarvey/nginx-php-fpm:1.2.0
    # restart: always
    expose:
     - "80" #required for nginx-proxy
    links:
      - mysql
      - redis
    environment:
      - VIRTUAL_HOST=oca.* #https://github.com/jwilder/nginx-proxy, camma separate for multiples
      # - OCTOBER_PLUGINS=October.Drivers;RainLab.GoogleAnalytics;Offline.Speedy;Rainlab.User;clake.userextended;Rainlab.Forum;
      - OCTOBER_DB_DRIVER=mysql
      - OCTOBER_DB_HOST=mysql
      - OCTOBER_DB_PASSWORD=password
      - OCTOBER_DB_NAME=octobercms
      - OCTOBER_DB_USER=octobercms
      - OCTOBER_APP_KEY=Idgz1PE3zO9iNc0E3oeH3CHDPX9MzZe3
      - ERRORS=1
      - RUN_SCRIPTS=1
      - ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=remote_host=192.168.111.27
      - PHP_IDE_CONFIG=serverName=docker
      #- DO_NOT_COPY_OCTOBER_CONFIG=1
      - SKIP_COMPOSER=1
    volumes:
      - ./pluginsThemes/themes/:/var/www/html/src/themes
      - ./pluginsThemes/plugins/:/var/www/html/src/plugins
    depends_on:
      - 'mysql'
  mysql:
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=octobercms
     - MYSQL_USER=octobercms
     - MYSQL_PASSWORD=password
  adminer:
    image: clue/adminer
    expose: 
      - "80"
    ports:
      - "8081:80"
    links:
      - mysql
    environment:
      - VIRTUAL_HOST=db.*
  redis:
    image: "redis"
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

# from https://github.com/jwilder/nginx-proxy/issues/502
# I also have to put this at the bottom of all other dev docker-compose files.
# I ran this as well, needs to be run once per docker SERVER: docker network create nginx-proxy
#     This is needed so nginx-proxy can be used across compose files.
networks:
  default:
    external:
      name: nginx-proxy
